Update pylint.yml

diff --git a/.github/workflows/pylint.yml b/.github/workflows/pylint.yml
--- a/.github/workflows/pylint.yml
+++ b/.github/workflows/pylint.yml
@@ -21,20 +21,20 @@ jobs:
     - name: Analysing the code with pylint
       run: |
         pylint $(git ls-files '*.py')
-    - name: Check pylint score
-      id: pylint-check
-      run: |
-        pylint_score=$(pylint $(git ls-files '*.py') | grep 'Your code has been rated at' | sed -E 's/.* ([0-9.]+)/\1/')
-        if (( $(echo "$pylint_score > 5" | bc -l) )); then
-          echo "Pylint score is greater than 5, success"
-          exit 0
-        else
-          echo "Pylint score is less than or equal to 5, failure"
-          exit 1
-        fi
-    - name: Set build status
-      if: steps.pylint-check.outcome == 'success'
-      run: echo "Pylint check passed, build successful"
+    # - name: Check pylint score
+    #   id: pylint-check
+    #   run: |
+    #     pylint_score=$(pylint $(git ls-files '*.py') | grep 'Your code has been rated at' | sed -E 's/.* ([0-9.]+)/\1/')
+    #     if (( $(echo "$pylint_score > 5" | bc -l) )); then
+    #       echo "Pylint score is greater than 5, success"
+    #       exit 0
+    #     else
+    #       echo "Pylint score is less than or equal to 5, failure"
+    #       exit 1
+    #     fi
+    # - name: Set build status
+    #   if: steps.pylint-check.outcome == 'success'
+    #   run: echo "Pylint check passed, build successful"
     # - name: Set build status
     #   if: steps.pylint-check.outcome == 'failure'
     #   run: echo "Pylint check failed, build failed"
